### ISSUE TITLE
Remove vendor from .gitignore file

### ISSUE THREAD

**Issue by zhengpenghu** [jaxonwang/jaxonwang.github.io#2]
This is a hidden bug. Otherwise, you may see an issue like https://github.com/mmistakes/minimal-mistakes/issues/1606.

**Comment by jaxonwang** [comment]
Thanks a lot. I didn't know there is also a vendor dir in _ssas/so-simple. Now only the jaxonwang.github.io/vendor excluded.

**Comment by zhengpenghu** [comment]
Glad to help :)
